### ISSUE TITLE
Server selection

### ISSUE THREAD

**Issue by sschueller** [sschueller/peertube-android#1]
When first opening the app it should connect to a server which needs to be determined somehow.

- Auto select from a list?
- Auto discover via some service?
- Ability to change when registering or login in.

**Comment by sschueller** [comment]
Added some stubs to the code, server list can be pulled from https://instances.joinpeertube.org/api/v1/instances?start=0&count=1000 but requires a UI to select one and possible provide a filter as well. Additionally we need to find out if the server is reachable via SSL or not as the API doesn't seem provide this information (Is peertube always over SSL?).

**Comment by Nutomic** [comment]
The [setup instructions](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#webserver) imply that SSL is required for all instances. ping @rigelk

**Comment by rigelk** [comment]
@Nutomic indeed it's always over SSL/TLS.

**Comment by lishoujun** [comment]
https://instances.joinpeertube.org/api/v1/instances?start=0&count=1000
this link is very usefully,I find a good(with more video and lower net delay) instance.

**Comment by sschueller** [comment]
It is now possible to keep a server address book and select from instances listed at https://instances.joinpeertube.org
