### ISSUE TITLE
Suggestion: allow search history to be deleted

### ISSUE THREAD

**Issue by catfluoride** [sschueller/peertube-android#102]
Hi,

it would be nice to allow the search history to be deleted, for the sake of privacy. Maybe with a long press on the suggestion field or adding a button in the app settings.

Thanks a lot.

**Comment by chin123** [comment]
Hey, I'd like to work on this, is there any specific process I should follow before I contribute or should i just send a PR?

**Comment by sschueller** [comment]
At this point you can just send a PR. I will assign the issue to you for now.

**Comment by dhk2** [comment]
I went with a long press on the magnifying glass bringing up a confirmation dialog to clear the history.

**Comment by sschueller** [comment]
Thank you @dhk2.
