### ISSUE TITLE
Move translation to dedicated platform

### ISSUE THREAD

**Issue by s8321414** [sschueller/peertube-android#107]
I will suggest to move translation to dedicated platform along with GitHub, it will be easier to maintain translation, and I may suggest [Weblate](https://hosted.weblate.org/).

**Comment by lishoujun** [comment]
I think two platform will make it more complex,this is only a little project now.

**Comment by sschueller** [comment]
I have requested a free account at weblate but have not heard back yet.  It should be quite easy to do translations on weblate for anyone and then submit a pull request from there. I will update this issue once I hear back from weblate.

**Comment by sschueller** [comment]
The repo has been added by weblate. You can now easily make translation here: https://hosted.weblate.org/projects/peertube/android/
