### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by ghost** [sschueller/peertube-android#11]
Hello!

This would be a great app to have on F-Droid!

**Comment by lramage94** [comment]
Awesome! If you need any help let me know!

**Comment by sschueller** [comment]
There is a pull request for Peertube on f-droid now but it needs to be test built before it will be merged. If anyone has sometime to see if it will build with `fdroid build` please let me know in the pull request: https://gitlab.com/fdroid/fdroiddata/merge_requests/3918

**Comment by Nutomic** [comment]
It is already available from IzzyOnDroid's repo :)

https://android.izzysoft.de/articles/named/izzyondroid_repo_1

**Comment by sschueller** [comment]
I see google play services listed as an anti feature. I will try to remove it, I don't think it is needed.

**Comment by sschueller** [comment]
App has now been merged into the main fdroid repo.
