### ISSUE TITLE
prerelease can not access by api ,please make a release

### ISSUE THREAD

**Issue by lishoujun** [sschueller/peertube-android#121]
https://developer.github.com/v3/repos/releases/

> Get the latest release
> View the latest published full release for the repository. Draft releases and prereleases are not returned by this endpoint.

**Comment by sschueller** [comment]
Just curious, where are you consuming the API?

**Comment by lishoujun** [comment]
[![Latest release](https://img.shields.io/github/release/sschueller/peertube-android.svg)](https://github.com/sschueller/peertube-android/releases/latest)

 Add release info to readme
