### ISSUE TITLE
Change description on F-Droid

### ISSUE THREAD

**Issue by rigelk** [sschueller/peertube-android#128]
Following up on https://github.com/Chocobozzz/PeerTube/issues/1624, a first measure to take would be to have a description explaining what to expect from the app, especially with regard to the PeerTube platform and network of instances.

#### n°1: description

current desciption:

> PeerTube is a federated (ActivityPub) video streaming platform using P2P (WebTorrent) directly in the web browser.

It is a very technical description, only fitting the GitHub headline description, so let me suggest that one instead:

> PeerTube is a federated video streaming platform that is community-owned and ad-free, with no vendor lock-in. This client allows you to watch and browse videos on a server of your choice in the PeerTube network.
>
> This client comes preconfigured with one PeerTube server managed by the application creator - not the PeerTube project itself, which lists more on http://instances.joinpeertube.org/ - to allow you to have a taste of what the client is capable of. Choose your server to tune your experience!

#### n°2: summary

current headline:

> PeerTube player

suggested headline:

> a PeerTube player

#### n°3: non-release status

This one is trickier. While you can and have tagged your client as non-release on the Play store, there is no indication whatsoever of its alpha/beta/non-release state on the F-Droid app presentation. The lack of annotation (akin to semver) of the versions put of F-Droid (ex: 1.0.24-alpha or 1.0.24-unstable) is not helping too.

I would suggest you change your release naming, or at least put an additional warning in the description and summary.

**Comment by sschueller** [comment]
Thank you for the text. I will submitting the changes to fdroid as soon as I can and rename the release tag if I can.

**Comment by sschueller** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/4474
