### ISSUE TITLE
available server list should update automatically

### ISSUE THREAD

**Issue by andy5995** [sschueller/peertube-android#141]
For example, https://peervideos.com/ has been inaccessible for ~2 weeks

I first found peervideos.com [here](https://instances.joinpeertube.org/instances) and it's since been removed from the listing.

**Comment by sschueller** [comment]
The list is pulled from `https://instances.joinpeertube.org/instances` every time you open the selection. However at the moment there is no check to see if the server you are currently using is still listed.
