### ISSUE TITLE
Downloaded video have no title but only numbers

### ISSUE THREAD

**Issue by mouarfff** [sschueller/peertube-android#143]
Hello,

I often use donwload function but the video downloaded have no title but only numbers

**Comment by sschueller** [comment]
There appear to be some issues with utf8 characters. 

Android pre launch report:

Exceptions
java.lang.IllegalArgumentException: Invalid file URI: file:///storage/emulated/0/Download/✯❊ Online My Hero Academia: Heroes Rising [2019] Full~Movie.Free..mp4
