### ISSUE TITLE
Incrementing #Views" number upon watching a video?

### ISSUE THREAD

**Issue by tukoz** [sschueller/peertube-android#152]
Watching a video from first to last second on Thorium doesn't increment the number of views for that video, either via Thorium ("Search") or on the video's instance (using https://pe.ertu.be). Is that by application design or can it be implemented?

Thorium 1.0.30 - Android 8.1 on a PlanetPC Gemini.
PS: Thorium great speed an KISS design much appreciated here :D

**Comment by sschueller** [comment]
I am going to close this. The view count is managed by the server. It would require additional polling to get this data and peer tube may change the frequency at which views are updated just like youtube so it won't be imidate.
