### ISSUE TITLE
Thorium for Desktop via Flathub

### ISSUE THREAD

**Issue by ghost** [sschueller/peertube-android#158]
[flathub.org](https://flathub.org) is a very popular app center for GNU/Linux and a lot of people are visiting it. I think it's very important for Thorium to be there, this way more people will discover this project.

https://github.com/flathub/flathub/wiki/App-Submission

**Comment by sschueller** [comment]
From my understanding these are Linux apps that flathub provides. As Thorium is Android only this is not something I will be able to do at this time
