### ISSUE TITLE
Option to hide NSFW content

### ISSUE THREAD

**Issue by maxigaz** [sschueller/peertube-android#16]
It would be great if the client had an option to hide videos with NSFW content, which is enabled by default.

**Comment by sschueller** [comment]
I added the option but I am waiting on https://github.com/Chocobozzz/PeerTube/issues/760 before I can implement it.

**Comment by sschueller** [comment]
Implemented in v1.0.1-alpha

**Comment by DI555** [comment]
The feature's not bad! Pardon me), but logically the switch must switch the futire, not unfuture!!!
So would be right (in logic), if the option be named smth. like ' Use NSFW restriction ' and it be working when switch 'on'.
