### ISSUE TITLE
Application crashes after sign in

### ISSUE THREAD

**Issue by kotovalexarian** [sschueller/peertube-android#165]
I've signed to my PeerTube account (https://video.autizmo.xyz instance). The application have redirected me to start screen and then it have disappeared. After restart it crashes.

I have OnePlus 6 with OxygenOS 10.3.2 (Android 10).

![photo_2020-06-07_23-10-23](https://user-images.githubusercontent.com/44363825/83976815-d28bb500-a915-11ea-9bf1-74caf39036b1.jpg)

**Comment by kotovalexarian** [comment]
The same happens when signing in to my own instance https://peertube.crypto-libertarian.com

**Comment by sschueller** [comment]
In the latest version v1.0.38, there is now a server book. Please try again and let me know if you have login issues.
