### ISSUE TITLE
Fullscreen Video

### ISSUE THREAD

**Issue by miasmaejuices** [sschueller/peertube-android#18]
Firstly - great work so far on the app. I'm finding it to be moving at a good pace.

My question/request is to ask if full screen video has been implemented as yet? If not, then I'd like to request it as a future. It's the only thing stopping me from switching my kids to a self hosted instance.

Contrary to other requests I've read, the lack of more advanced configuration options is actually a bonus in my case, as it means my kids candidate damage the configuration as simply as other options out there.

As a side note, adding an optional custom pin number to the settings screen would also be very nice 😊👍

Thanks for the great work!

**Comment by sschueller** [comment]
Fullscreen video implemented in Implemented in v1.0.1-alpha. For a child lock feature please open new issue. Thanks

**Comment by DI555** [comment]
I found undocumented feature. Please keep it as option in a future!
Full screen is activated when rotate beetwen vertical and horizontal positions!
