### ISSUE TITLE
Inconsistant layout design for server list screen

### ISSUE THREAD

**Issue by digiwizkid** [sschueller/peertube-android#183]
The server list screen is not having an action bar/ toolbar which is a bit confusing and is not consistent with the whole app.

The subscription menu from the bottom nav menu is opening the server list screen.

![Screenshot_20200624-200654](https://user-images.githubusercontent.com/16302424/85578453-b13a0100-b657-11ea-9d39-c08c4d247237.png)

**Comment by sschueller** [comment]
I will be fixing the layouts shortly. The subscription takes you to the server list if you are not logged in. I will think of something to make this more clear.
