### ISSUE TITLE
When in PiP video can not be stopped

### ISSUE THREAD

**Issue by sschueller** [sschueller/peertube-android#192]
When using PiP the notification is missing the stop button.  There is also no stop/close button anywhere else making it impossible to dismiss the notification.

I think the best solution would be to add a close button (X) to the notification just like the youtube app does it.
![photo_2020-06-28_22-11-26](https://user-images.githubusercontent.com/1180107/85957279-5b819380-b98c-11ea-8274-79a6a0cad3da.jpg)

**Comment by dhk2** [comment]
Working on it

**Comment by sschueller** [comment]
https://github.com/sschueller/peertube-android/pull/195
