### ISSUE TITLE
Some video cannot be played

### ISSUE THREAD

**Issue by freeboub** [sschueller/peertube-android#233]
Some video cannot be played (even make the application crash)

You can find a sample on thinker instance, on thinkerview video:
https://thinkerview.video/videos/watch/00eb921c-0a8f-4bf2-8f94-a5a93bc4ae8b

I already avoid the crash in : https://github.com/sschueller/peertube-android/pull/231

The explanation of this crash is explained here:
https://framacolibri.org/t/video-json-missing-files-field/8908

ie sometimes `files` is empty and should be retrieved from `streamingPlaylists`.

**Comment by freeboub** [comment]
I have already implemented a local patch: parse streamingPlaylists and use it is files is empty.
I can read the video, but exoplayer doesn't display playback time correctly ... (It stays always 5 seconds, where position is increasing)
I also try to upgrade exoplayer to 2.12.0, now position and duration are increasing ...

**Comment by sschueller** [comment]
Related https://github.com/sschueller/peertube-android/issues/181 ?

**Comment by freeboub** [comment]
I don't think so, in that case there is no video url at all. The url cannot be parsed from server!

**Comment by dhk2** [comment]
yeah, this seems to be a symptom of the problem I was running into with sites that no longer support legacy webtorrents, thus there is no way to make it work with the torrent player because it indicates that the site doesn't have torrent compatible files
