### ISSUE TITLE
Sharing links to Thorium

### ISSUE THREAD

**Issue by LibreHacker** [sschueller/peertube-android#235]
Like your people send link (maybe in Conv6ations or others) to PeerTube video and not need open it in browser for viewing.

It's can working with https://framagit.org/tom79/nitterizeme/-/issues/44 , if you add support for it.

**Comment by sschueller** [comment]
See discussion over at peertube: https://github.com/Chocobozzz/PeerTube/issues/1540 . Once there is a solution on the peertube side this can be implemented.
