### ISSUE TITLE
No acept SSL self-signed

### ISSUE THREAD

**Issue by AnonymousWebHacker** [sschueller/peertube-android#237]
my peertube instance is fully decentralized, my server uses self-signed certificate. peertube apk won't let me accept the SSL certificate, like google chrome or Firefox does

**Comment by sschueller** [comment]
I will check if its possible to add a button in the settings to ignore if the certificate is valid.

**Comment by AnonymousWebHacker** [comment]
@sschueller this is an example of element android.
![Uploading 83937697-a54de280-a801-11ea-82f7-1dc09813b8fc.png…]()

**Comment by AnonymousWebHacker** [comment]
@sschueller Sorry. The question, but I am anxious about the update that you fix, this of the certificates. When would the update come out?

**Comment by sschueller** [comment]
At the moment I am very busy so it will probably take a while. I will however look at it next.

**Comment by AnonymousWebHacker** [comment]
In my case I am already using valid certificates in my instance, however, I do not know whether to close the committee or leave it for other people who need this implementation.
Thanks for answering

**Comment by sschueller** [comment]
Added in Release v1.0.50

**Comment by AnonymousWebHacker** [comment]
Very much tnks, I convey the thanks of my more than 1000 users on my snet
