### ISSUE TITLE
Add the option to accept self signed certificate

### ISSUE THREAD

**Issue by luky92** [sschueller/peertube-android#238]
I have a peertube instance in a local network as such I can't use ssl certificate other then self signed due to that I'm unable to use the app so it would be great if you added an option to bypass ssl checks when connecting to the server

**Comment by sschueller** [comment]
Do you have or know of a public insecure instance I can test with?

**Comment by luky92** [comment]
i can create an instance like that for testing only

**Comment by sschueller** [comment]
Here is a test version with an option under preferences to enable insecure connections. Warning it will require you to remove any existing version you may have installed and you will loose your saved instances list. You can also email me the address of the test instance (if you do not want to post it publicly here) and I can test it directly. Thanks
[app-release.zip](https://github.com/sschueller/peertube-android/files/5542589/app-release.zip)

**Comment by luky92** [comment]
Well that version logged in but didn't play the videos. I sent you an email with the instance info

**Comment by sschueller** [comment]
Thanks, I will work on it.

**Comment by sschueller** [comment]
Here is another version that should play the videos. If OK I will release it soon, have to see if this has issues with the play store. I might have to add an additional warning to the settings.
[Uploading app-release.zip…]()

**Comment by luky92** [comment]
Hi,
yest that version play videos perfectly and works with my local instance however it doesn't download miniatures (don't know if it should as both instances behave the same). As for the test instance it will stay as long as its needed just let me know when its no longer needed

**Comment by sschueller** [comment]
Added in Release v1.0.50
