### ISSUE TITLE
What license, GPL or AGPL?

### ISSUE THREAD

**Issue by jeena** [sschueller/peertube-android#239]
I'm confused, the LICENSE file says it's AGPL, the README file has a button which says it's GPL and in the individual files it also says it's GPL. It would be good if this was consolidated to not have too much confusion about the license.

**Comment by sschueller** [comment]
The license is AGPL, same as the peertube project. I Will clean up the files that say GPL. Thanks for letting me know.

**Comment by sschueller** [comment]
All files should match now
