### ISSUE TITLE
No video only sound

### ISSUE THREAD

**Issue by sifourquier** [sschueller/peertube-android#240]
Hi
When I play a movie I have black image in place of video  (in full screen is full black screen). But sound work fine.

I have a Samsung xcover pro.

**Comment by sschueller** [comment]
Hi, can you give me the URL of the video? It may be an issues with exoplayer not being able to play that codec. Related to this issue: https://github.com/sschueller/peertube-android/issues/181

**Comment by sifourquier** [comment]
It's strange
First time I run app I try ~5 movie and all black with sound.
After you reply I try 3 other movie not work but the 4th work and now all work.

**Comment by sschueller** [comment]
I have found a bug where the ```0p``` video some servers provide is selected which contains no video. Fix will be in next release.
