### ISSUE TITLE
F-Droid Build is failing

### ISSUE THREAD

**Issue by sschueller** [sschueller/peertube-android#258]
CI script needs to be debugged

**Comment by licaon-kter** [comment]
Yup, https://f-droid.org/wiki/index.php?title=net.schueller.peertube/lastbuild_1056&oldid=286732 since versionName and Tag are expected to be in sync.

**Comment by sschueller** [comment]
This should be fixed now.

**Comment by neunenak** [comment]
Should this fix cause new builds to appear in the f-droid store? As of right now, it looks like the latest available Thorium build there is Version 1.0.48 (1048) - Added on 2020-10-28

**Comment by sschueller** [comment]
I do not know when fdroid will try to build again. I assume after a failed build they will not try to build every day after but maybe every week until builds work again.

**Comment by sschueller** [comment]
Latest build passed so it should show up shortly. https://f-droid.org/wiki/page/net.schueller.peertube/lastbuild_1058
