### ISSUE TITLE
after adding a new instance thorium client crashes

### ISSUE THREAD

**Issue by eggercomputerchaos** [sschueller/peertube-android#268]
hi,
thorium crashes after I added a new peertube instance.
device: galaxy s5 klte
os: los-microg 17.1

log file attached

thx for looking at it

[2021-04-09-thorium crash.txt](https://github.com/sschueller/peertube-android/files/6286233/2021-04-09-thorium.crash.txt)

best

**Comment by sschueller** [comment]
The issue maybe that this server (https://tube.ourvideos.org/) is running peertube version 2.3.0 which is quite old.

**Comment by eggercomputerchaos** [comment]
thx,
I will ask for updating the peertube version on this server.
but quite old - from 21 Jul 2020?????

**Comment by eggercomputerchaos** [comment]
after update to peertube version 3.1.0 
it works :-)
thx
