### ISSUE TITLE
Distribute your app through Flathub/Flatpak

### ISSUE THREAD

**Issue by andrew712-1** [sschueller/peertube-android#282]
**https://flathub.org**

[LBRY](https://flathub.org/apps/details/io.lbry.lbry-app) is already on Flathub, it's sad that Peertube stays behind, we should be there as well, especially when we know that Peertube is much better, privacy-respecting and actually decentralized!

- [ ] [How to submit an app on Flathub](https://github.com/flathub/flathub/wiki/App-Submission)

**Comment by sschueller** [comment]
Flatpack are Linux applications. Thorium is only for android at this point.

**Comment by andrew712-1** [comment]
@sschueller is it hard to package it for Linux?

**Comment by sschueller** [comment]
@andrew712-1 It would require pretty much a complete rewrite of the app for desktop use. At this point I want to focus on Android as that already take a lot of time. Maybe someone wants to write a wrapper in Electron or so but there might be little benefit. There is no official youtube app for desktop either.
