### ISSUE TITLE
Does thorium use https://search.joinpeertube.org ?

### ISSUE THREAD

**Issue by niccokunzmann** [sschueller/peertube-android#288]
I was wondering about how the search is implemented. It seems like Thorium is asking the instances that are in the address book.
I would really appreciate using
https://search.joinpeertube.org
I do not know which instances to subscribe to but I would like to have something like a Youtube search for all Videos on all instances. Best, if I can configure the URLs by f where to search, too.

**Comment by sschueller** [comment]
At the moment it is using the one from each host. There is already an issue regarding this https://github.com/sschueller/peertube-android/issues/151
