### ISSUE TITLE
Cannot view other servers

### ISSUE THREAD

**Issue by RetroJimmyX** [sschueller/peertube-android#295]
From the intro, I understand Thorium comes pre-configured to work with a particularly peertube server but I cannot see how to change settings to work with any other(s). Please advise.

**Comment by sschueller** [comment]
There's an icon on the top corner that looks like 2 servers. If you click that it takes you to the address book where you can add as many servers as you want.

**Comment by RetroJimmyX** [comment]
I'm so sorry for raising the issue, I don't know why my brain just ignored that icon. Working perfectly. Thanks!
