### ISSUE TITLE
Android 5 support, please!

### ISSUE THREAD

**Issue by DI555** [sschueller/peertube-android#43]
There're tons of android 5 mobile phone and android 5 mods of it.
Please add support of android 5!
Or if would be easier, as dominant of it, imho minimal support of android 5.1 would be enough!
Many thanks in advance!

**Comment by sschueller** [comment]
I will look into it.

**Comment by sschueller** [comment]
I have added support for `minSdkVersion 21` in `v1.0.7` but I don't know if it works. I was able to start the app in the Emulator on Android 5. Please let me know if playback works ok. Thanks

**Comment by DI555** [comment]
Yes, working great! Just was testing to find out that no bugs but not-polished things.

**Comment by sschueller** [comment]
I will close this for now. If there are any major issues please open a new issue.
