### ISSUE TITLE
Oreo adaptive icon shape

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [sschueller/peertube-android#48]
Please add support for icon shape

https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

**Comment by sschueller** [comment]
Implemented in v1.0.10

**Comment by 532910** [comment]
Looks like new icon isn't adaptive, please reopen.
![IMG_20191202_205237](https://user-images.githubusercontent.com/14617699/69982674-13a9a380-1546-11ea-888d-c8f7764ba235.jpg)
