### ISSUE TITLE
Playback speed and video quality selection option

### ISSUE THREAD

**Issue by digiwizkid** [sschueller/peertube-android#51]
Any plan to introduce these features?
I would like to contribute to implementing these features, please direct me to the relevant documentation.

**Comment by sschueller** [comment]
You are welcome to implement these features if you want.

I use the exoplayer2 (https://github.com/google/ExoPlayer) which is the same used by the youtube app. Speed and quality should be doable. 

Speed can be set with `setPlaybackParameters()`

For quality you would need to do a bit more work to find out which are available and then offer those options. Currently the app takes the first item in the files array which contains all the video resolutions. The activity would need to hand over the new file to be played to the video player service.

Let me know if you want to implement these and I will hold off on implement them myself.

Thanks

**Comment by digiwizkid** [comment]
I am looking into the playback speed feature right now, will keep you updated on that.

**Comment by sschueller** [comment]
Yes, in v1.0.13 👍

**Comment by c-e-p-x-u-o** [comment]
(:
