### ISSUE TITLE
another sound stream must be paused

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [sschueller/peertube-android#55]
when i press play it plays together with another sound steam (newpipe for example) and i need to pause or manually

**Comment by sschueller** [comment]
Fixed in v1.0.15

**Comment by 532910** [comment]
Confirm, fixed.
But it's better to pause another sound steam that time you are ready to play, not that time user press play.

Same as newpipe does.

For example I play locally saved music album with VLC. If I have network issues and press play in Thorium the VLC will be paused, but nothing starts play.
