### ISSUE TITLE
playing must be stopped by back button

### ISSUE THREAD

**Issue by 532910** [sschueller/peertube-android#57]
i open the video, it starts playing
i press back, to go to the home screen, but the video continue playing in the background

**Comment by sschueller** [comment]
This should probably be controllable behavior via a preference.

**Comment by c-e-p-x-u-o** [comment]
it must be stopped or must be controllable

**Comment by DI555** [comment]
Anyway, optionable is way better!

**Comment by dhk2** [comment]
Pausing playback on the back button so playback can be resumed by the notification area controls seems a better behavior than stopping.

**Comment by 532910** [comment]
Nope. I'm agree to remember position, but there should be no notification pressing the back button.

**Comment by sschueller** [comment]
I like the way youtube does it with the notification and an ability to close the notification.
![photo_2020-06-28_22-11-09](https://user-images.githubusercontent.com/1180107/85957280-5cb2c080-b98c-11ea-8ec0-73128ac2bcca.jpg)
![photo_2020-06-28_22-11-26](https://user-images.githubusercontent.com/1180107/85957279-5b819380-b98c-11ea-8274-79a6a0cad3da.jpg)

**Comment by sschueller** [comment]
This has been implemented
