### ISSUE TITLE
Background color of playing video.

### ISSUE THREAD

**Issue by DI555** [sschueller/peertube-android#60]
I'd like to suggest an option to choose background color of playing video!( I mean background - the place where video is playing and scaled to the borders of screen)
Before last build it was was only black, but now white with nornal mode and grey with dark mode.
I whould suggest a bunch of grey scale with black and white as well.( slider scale from white to black(?))
Many thanks in advance.

**Comment by sschueller** [comment]
I think background for a video should always be black. We can add a color change feature at a later time. I set this as a bug for now.

**Comment by sschueller** [comment]
I have fixed the default. Changing colors we made add in the future, thanks.
