### ISSUE TITLE
[Enhancement] Fullscreen Button

### ISSUE THREAD

**Issue by Nathoufresh** [sschueller/peertube-android#67]
It would be nice for those who use to lock the rotation to have a button to play fullscreen.

**Comment by sschueller** [comment]
Added in v1.0.16

**Comment by DI555** [comment]
Not worked like was asking. Should be added 2 buttons - 'full screen' button and 'pin' button to lock the screen in the position what's chosen (4 various positions)!

**Comment by sschueller** [comment]
Do you have an example app (play store link) I can look at to see how the UI should work?

**Comment by DI555** [comment]
I don't have an example yet(. But here was asking about not only for 'full screen button' , but with fixed position. So 'full screen button' should work like right now but screen should be sensitive to its orientation(theese examples I've seen) - 4 positios:vertical, horizontal and 2 its reversed,  
;and the another 'pin' button should locate the current screen orientation and pin it.

ps
I used to use before and now in PT the undocumented full screen mode, when rotate the screen it switched fullscreen on ;). Please don't break it, it's so powerfull)!
