### ISSUE TITLE
Need a peertube server book, so I can switch between different servers

### ISSUE THREAD

**Issue by lishoujun** [sschueller/peertube-android#70]
Now there can only put one link.
I need a peertube server book, so I can switch between different servers.

**Comment by andy5995** [comment]
Isn't this a duplicate of #1?

**Comment by andy5995** [comment]
@sschueller this was implemented and can be closed, right?

**Comment by sschueller** [comment]
@andy5995 the list is implemented however I also wanted to add a way to be able to switch and have credentials attached to servers.
