### ISSUE TITLE
add a language filter

### ISSUE THREAD

**Issue by lishoujun** [sschueller/peertube-android#80]
I only speak Chinese and English,now there are too many other language video, on the web client I can filter them, but now on android client still cannt.

I want to add a language filter below setting->nsfw
Is this position OK，or you have other plan to put all  useful Filters .
I am looking for your opinion.

**Comment by sschueller** [comment]
This is something I would like to add and should not be too complicated

**Comment by sschueller** [comment]
in Release v1.0.19. Thank you.
